### ISSUE TITLE
navbar overlapping the content

### ISSUE THREAD

**Issue by qsz13** [fanghuang/Tongji#3]
![image](https://cloud.githubusercontent.com/assets/4075761/6864122/11633864-d498-11e4-8de1-f2bc3fc1663b.png)

The navbar is overlapping the content, should it be navbar-fixed-top or navbar-static-top? if it is navbar-fixed-top then maybe we need to set a padding for body according to this:

http://stackoverflow.com/questions/11124777/twitter-bootstrap-navbar-fixed-top-overlapping-site

**Comment by vanakema** [comment]
I put in the commit log that it was not quite ready yet. We're still
working on so please don't move it yet. I pushed it because Peter wanted to
be able to work on it without me

**Comment by qsz13** [comment]
sure, I will not modify the raw_pages folder directly and only copy them to the template folder to make modification. I'm opening this issue incase you haven't noticed it.
